brctl addbr vbr-pext
brctl stp vbr-pext off
ip link set dev vbr-pext up
ip netns add qgw
ip link add veth0 type veth peer name qgw-veth0.t
ip link set veth0 netns qgw
brctl addif vbr-pext qgw-veth0.t
ip link set dev qgw-veth0.t up
mkdir -p /etc/netns/qgw
chmod -R 777 /etc/netns/qgw
touch /etc/netns/qgw/hosts
chmod 777 /etc/netns/qgw/hosts
echo "# auto-generated by magnet" > /etc/netns/qgw/hosts
echo "127.0.0.1    localhost" >> /etc/netns/qgw/hosts
echo "" >> /etc/netns/qgw/hosts
echo "10.0.131.1    qgw" >> /etc/netns/qgw/hosts
echo "10.0.131.2    qhost1" >> /etc/netns/qgw/hosts
ip netns exec qgw ip link set lo up
ip netns exec qgw ip addr add 10.0.131.1/24 dev veth0
ip netns exec qgw ip link set veth0 up
ip netns add qhost1
ip link add veth0 type veth peer name qhost1-veth0.t
ip link set veth0 netns qhost1
brctl addif vbr-pext qhost1-veth0.t
ip link set dev qhost1-veth0.t up
mkdir -p /etc/netns/qhost1
chmod -R 777 /etc/netns/qhost1
touch /etc/netns/qhost1/hosts
chmod 777 /etc/netns/qhost1/hosts
echo "# auto-generated by magnet" > /etc/netns/qhost1/hosts
echo "127.0.0.1    localhost" >> /etc/netns/qhost1/hosts
echo "" >> /etc/netns/qhost1/hosts
echo "10.0.131.1    qgw" >> /etc/netns/qhost1/hosts
echo "10.0.131.2    qhost1" >> /etc/netns/qhost1/hosts
ip netns exec qhost1 ip link set lo up
ip netns exec qhost1 ip addr add 10.0.131.2/24 dev veth0
ip netns exec qhost1 ip link set veth0 up
ip netns exec qhost1 route add default gw 10.0.131.1
